
.TH "vme_set_bus_request_mode" 3

.SH "NAME"
vme_set_bus_request_mode - Sets the VMEbus request mode.


.SH "SYNOPSIS"
int vme_set_bus_request_mode
.br
(
.br
.in +5
vme_bus_handle_t bus_handle,
.br
int br_mode
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t bus_handle
.br
.in +5

.br
Handle allocated by vme_init(3)
.

.br

.in
.br

.B int br_mode
.br
.in +5

.br
Bus request mode. Valid values are:

.br

.nf
- VME_DEMAND
.fi

.nf
- VME_FAIR
.fi

.in
.br


.SH "DESCRIPTION"

.br
Sets the VMEbus request mode.

.br

.SH "RETURNS"


.br
0 on success, or -1 on failure.

.br


.SH "SEE ALSO"
vme_get_bus_request_mode(3)
.br
