
.TH "vme_dma_buffer_phys_addr" 3

.SH "NAME"
vme_dma_buffer_phys_addr - Not used.


.SH "SYNOPSIS"
void * vme_dma_buffer_phys_addr
.br
(
.br
.in +5
vme_bus_handle_t bus_handle,
.br
vme_dma_handle_t handle
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t bus_handle
.br
.in +5

.br
Handle allocated by vme_master_init(3)
.

.br

.in
.br

.B vme_dma_handle_t handle
.br
.in +5

.br
 DMA handle allocated by vme_dma_buffer_create(3)
.

.br

.in
.br


.SH "DESCRIPTION"

.br
Not used.

.br

.SH "RETURNS"


.br
return -1.

.br


.SH "SEE ALSO"
vme_dma_buffer_create(3), vme_dma_buffer_map(3), vme_dma_buffer_release(3), vme_dma_buffer_unmap(3), vme_dma_read(3), vme_dma_write(3)
.br
