
.TH "vme_set_master_endian_conversion" 3

.SH "NAME"
vme_set_master_endian_conversion - Sets the Master Window endian conversion feature on or off.


.SH "SYNOPSIS"
int vme_set_master_endian_conversion
.br
(
.br
.in +5
vme_bus_handle_t bus_handle,
.br
int endian
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t bus_handle
.br
.in +5

.br
Handle allocated by vme_init(3)
.

.br

.in
.br

.B int endian
.br
.in +5

.br
A value of 1 turns on endian conversion. A value of 0 turns off endian conversion.

.br

.in
.br


.SH "DESCRIPTION"

.br
Sets the Master Window endian conversion feature on or off.

.br

.SH "RETURNS"


.br
0 on success, or -1 on failure.

.br


.SH "SEE ALSO"
vme_get_endian_conversion_bypass(3), vme_get_master_endian_conversion(3), vme_get_slave_endian_conversion(3), vme_set_endian_conversion_bypass(3), vme_set_slave_endian_conversion(3)
.br
