
.TH "vme_get_posted_write_count" 3

.SH "NAME"
vme_get_posted_write_count - Returns the transfer count at which the PCI slave channel posted a write FIFO.


.SH "SYNOPSIS"
int vme_get_posted_write_count
.br
(
.br
.in +5
vme_bus_handle_t bus_handle,
.br
int * pwon
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t bus_handle
.br
.in +5

.br
Handle allocated by vme_init(3)
.

.br

.in
.br

.B int * pwon
.br
.in +5

.br
Returns the transfer count, in number of bytes.

.br

.in
.br


.SH "DESCRIPTION"

.br
Returns the transfer count at which the PCI slave channel posted a write FIFO.

.br

.SH "RETURNS"


.br
0 on success, or -1 on failure.

.br


.SH "SEE ALSO"
vme_set_posted_write_count(3)
.br
