
.TH "vme_get_bus_release_mode" 3

.SH "NAME"
vme_get_bus_release_mode - Returns the current VMEbus release mode.


.SH "SYNOPSIS"
int vme_get_bus_release_mode
.br
(
.br
.in +5
vme_bus_handle_t bus_handle,
.br
int * br_mode
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t bus_handle
.br
.in +5

.br
Handle allocated by vme_init(3)
.

.br

.in
.br

.B int * br_mode
.br
.in +5

.br
Returns the current VMEbus release mode. Valid values are:

.br

.nf
- VME_RELEASE_ON_REQUEST
.fi

.nf
- VME_RELEASE_WHEN_DONE
.fi

.in
.br


.SH "DESCRIPTION"

.br
Returns the current VMEbus release mode.

.br

.SH "RETURNS"


.br
0 on success, or -1 on failure.

.br


.SH "SEE ALSO"
vme_set_bus_release_mode(3)
.br
