
.TH "vme_get_arbitration_timeout" 3

.SH "NAME"
vme_get_arbitration_timeout - Returns the current VMEbus arbitration timeout value.


.SH "SYNOPSIS"
int vme_get_arbitration_timeout
.br
(
.br
.in +5
vme_bus_handle_t bus_handle,
.br
int * to
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t bus_handle
.br
.in +5

.br
Handle allocated by vme_init(3)
.

.br

.in
.br

.B int * to
.br
.in +5

.br
Returns the VMEbus arbitration timeout value in microseconds. A value of 0 indicates that the timeout timer is disabled. Valid values are 0, 16 and 256.

.br

.in
.br


.SH "DESCRIPTION"

.br
Returns the current VMEbus arbitration timeout value.

.br

.SH "RETURNS"


.br
0 on success, or -1 on failure.

.br


.SH "SEE ALSO"
vme_set_arbitration_timeout(3)
.br
