
.TH "vme_init" 3

.SH "NAME"
vme_init - Initializes the VMEbus driver interface.


.SH "SYNOPSIS"
int vme_init
.br
(
.br
.in +5
vme_bus_handle_t * bus_handle
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t * bus_handle
.br
.in +5

.br
Pointer to the bus handle to allocate.

.br

.in
.br


.SH "DESCRIPTION"

.br
Initializes the VMEbus driver interface.

.br

.SH "RETURNS"


.br
0 on success, or -1 on failure.

.br


.SH "SEE ALSO"
vme_term(3)
.br
