
.TH "vme_register_image_release" 3

.SH "NAME"
vme_register_image_release - Disables the VMEbus register access image.


.SH "SYNOPSIS"
 vme_register_image_release
.br
(
.br
.in +5
vme_bus_handle_t bus_handle,
.br
vme_vrai_handle_t window_handle
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t bus_handle
.br
.in +5

.br
Handle allocated by vme_init(3)
.

.br

.in
.br

.B vme_vrai_handle_t window_handle
.br
.in +5

.br
Window handle allocated by vme_register_image_create(3)
.

.br

.in
.br


.SH "DESCRIPTION"

.br
Disables the VMEbus register access image.

.br

.SH "SEE ALSO"
vme_register_image_create(3)
.br
