
.TH "vme_dma_buffer_map" 3

.SH "NAME"
vme_dma_buffer_map - Returns the address of the buffer.


.SH "SYNOPSIS"
void * vme_dma_buffer_map
.br
(
.br
.in +5
vme_bus_handle_t bus_handle,
.br
vme_dma_handle_t handle,
.br
int flags
.in
)

.SH "PARAMETERS"

.B vme_bus_handle_t bus_handle
.br
.in +5

.br
Handle allocated by vme_master_init(3)
.

.br

.in
.br

.B vme_dma_handle_t handle
.br
.in +5

.br
Handle to a buffer allocated by vme_dma_buffer_create(3)
.

.br

.in
.br

.B int flags
.br
.in +5

.br
No flags are currently defined for this parameter; use 0.

.br

.in
.br


.SH "DESCRIPTION"

.br
Returns the address of the buffer.

.br

.SH "RETURNS"


.br
Pointer to mapped region on success, or NULL on failure.

.br


.SH "SEE ALSO"
vme_dma_buffer_create(3), vme_dma_buffer_phys_addr(3), vme_dma_buffer_release(3), vme_dma_buffer_unmap(3), vme_dma_read(3), vme_dma_write(3)
.br
